l_english:
u_wing_fighter_production_1:0 "U Wing MK 1"
u_wing_fighter_production_2:0 "U Wing MK 2"
e_wing_fighter_production_1:0 "E Wing"
a_wing_fighter_production_1:0 "A Wing MK 1"
a_wing_fighter_production_2:0 "A Wing MK 2"
k_wing_fighter_production_1:0 "K Wing"
x_wing_fighter_production_1:0 "X Wing MK 1"
x_wing_fighter_production_2:0 "X Wing Mk 2"
x_wing_fighter_production_3:0 "X Wing Mk 3"
y_wing_fighter_production_1:0 "Y Wing Mk 1"
y_wing_fighter_production_2:0 "Y Wing Mk 2"
b_wing_fighter_production_1:0 "B Wing Mk 1"
b_wing_fighter_production_2:0 "B Wing Mk 2"
tie_dagger_fighter_production_1:0 "Tie Dagger"
tie_silencer_fighter_production_1:0 "Tie Silencer"
tie_automated_fighter_production_1:0 "Tie Automated MK 1"
tie_automated_fighter_production_2:0 "Tie Automated Mk 2"
tie_fighter_production_1:0 "Tie Fighter Mk 1"
tie_fighter_production_2:0 "Tie Fighter Mk 2"
tie_fighter_production_3:0 "Tie Fighter Mk 3"
tie_fighter_production_4:0 "Tie Fighter Mk 4"
tie_interceptor_fighter_production_1:0 "Tie Interceptor Mk 1"
tie_interceptor_fighter_production_2:0 "Tie Interceptor Mk 2"
tie_interceptor_fighter_production_3:0 "Tie Interceptor Mk 3"
tie_interceptor_fighter_production_4:0 "Tie Interceptor Mk 4"
tie_fighterbomber_fighter_production_1:0 "Tie Aggressor Mk 1"
tie_fighterbomber_fighter_production_2:0 "Tie Aggressor Mk 2"
tie_fighterbomber_fighter_production_3:0 "Tie Aggressor Mk 3"
tie_bomber_fighter_production_1:0 "Tie Bomber Mk 1"
tie_bomber_fighter_production_2:0 "Tie Bomber Mk 1"
tie_bomber_fighter_production_3:0 "Tie Bomber Mk 1"
tie_bomber_fighter_production_4:0 "Tie Bomber Mk 1"